name: pokejava # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: PokeJava is a pokemon battle simulator written in Java. # 79 char long summary
description: |
  PokeJava is a pokemon battle simulator written in Java. It is currently run through the command line, though a
  graphical Java Swing implementation is in the works. The project is open-source and is available on GitHub
  at https://github.com/20avva/PokeJava.git.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  pokejava:
    command: java -jar target/PokeJavaApp-4.1.1.jar

parts:
  pokejava:
    # See 'snapcraft plugins'
    plugin: maven
    source: .
    build: |
      export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
      mvn clean test
    install: |
      mvn clean install
    build-packages:
      - unzip
      - openjdk-8-jdk
